import Head from 'next/head';
import Header from './components/Header';
import Main from './components/Main';
import Footer from './components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>JiTeam</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>

      <Header />

      <Main />
      <Footer />
    </div>
  );
}
