import Head from 'next/head';
import styled from '@emotion/styled';
import Header from './components/Header';
import Main from './components/Main';
import Footer from './components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <Main />
      <Footer />
    </div>
  );
}
